language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database stack;' -U postgres
- python database_setup.py
script:
- python -m pytest -v --cov app --cov-report term-missing
after_success:
- coveralls